// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gettingStartedSidebar: [{type: 'autogenerated', dirName: '00_getting_started'}],
  pcbDesignSidebar: [{type: 'autogenerated', dirName: '01_pcb_design'}],
  kicadSidebar: [{type: 'autogenerated', dirName: '02_kicad'}],
  schematicSidebar: [{type: 'autogenerated', dirName: '03_schematic-design'}],
  layoutSidebar: [{type: 'autogenerated', dirName: '04_layout'}],
  designPrinciplesSidebar: [{type: 'autogenerated', dirName: '05_design_principles'}],
  designWorkflowSidebar: [{type: 'autogenerated', dirName: '06_design_workflow'}],
  symbolsEeschemaSidebar: [{type: 'autogenerated', dirName: '07_symbols_eeschema'}],
  footprintsPcbnewSidebar: [{type: 'autogenerated', dirName: '08_footprints_pcbnew'}],
  projectsSidebar: [{type: 'autogenerated', dirName: '09_projects'}],
  recipesSidebar: [{type: 'autogenerated', dirName: '10_recipes'}],  
  electronicsSidebar: [{type: 'autogenerated', dirName: '11_electronics'}],  

};

export default sidebars;
